name: Release package to the Maven Central Repository

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.4'
      - name: Install protoc-gen-doc
        run: go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup semantic-release
        run: npm install -g @conveyal/maven-semantic-release semantic-release@15
      - name: Release
        run: semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch=dev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
